In [1]:
import numpy as np
import pandas as pd

# to visualize all the column, run the below code
pd.options.display.max_columns = None
# to show all the records, use the below code
# pd.options.display.max_rows = None

In [3]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv"
df = pd.read_csv(url)
df.shape

(128, 38)

In [4]:
df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,13,7,3,10,3,11,5,2,3,11,72,15,133,94,8,6,0,0,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,8,3,4,6,2,3,0,3,1,1,34,1,56,19,1,1,2,0,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,15,4,7,8,7,12,4,2,4,13,101,12,143,86,6,6,2,0,13,2,391,326,22,8,6,14,0,0

### `Q-1:` 
Find out the total percentages that each team made on target. Display the result as a python dictionary where the keys are the team list and the values are the percentage values. Round off the percentage values up to 2 decimal places.

*Help:*
- First, find out how many total teams are participated in this worldcup. For that, you can use `unique()` method on the column "Team" or "Against".
- Loop through the teams list that you have found in previous section, and then filter the dataset according to that. After filtering the dataset, find out total attempts sum and total on target sum.
- After getting these values, find out the percentage by total on target divided by total attempts and multiply by 100. And store to a python dictionary where the key will be the team name and the values will be the percentages.
- At the end,sort the dictionary by the values (not by the keys) and print the result.


**Sample Output:**
```bash
{'Costa Rica': 54.55,
 'Cameroon': 51.85,
 'Ecuador': 48.15,
 'Argentina': 46.99,
 'Brazil': 45.56,
 'England': 45.0,
 'Portugal': 40.32,
 'Ghana': 40.0,
 'Netherlands': 39.02,
 'Korea Republic': 36.73,
 'Australia': 36.0,
 'Mexico': 34.88,
 'Croatia': 34.78,
 'Germany': 34.33,
 'France': 32.97,
 'Spain': 32.69,
 'Belgium': 32.35,
 'Serbia': 32.26,
 'Iran': 31.43,
 'Uruguay': 31.25,
 'United States': 31.11,
 'Saudi Arabia': 31.03,
 'Senegal': 30.77,
 'Denmark': 30.56,
 'Switzerland': 30.56,
 'Japan': 30.23,
 'Wales': 29.17,
 'Qatar': 28.57,
 'Morocco': 28.3,
 'Tunisia': 26.67,
 'Poland': 25.0,
 'Canada': 17.65}
```

### `Q-2:` 
Find out how many times the teams played in this Fifa Worldcup-2022. On top of this, find out the ranks of the teams.

Note: The `DataFrame.rank()` method takes an optiinal parameter named `method`. This parameter takes different values, but one of them is `average` which is by-default. So, when you do the rank, you will get some 2.5 like floating values. But if you change the value as `first`, then you will get in integers but the datatype will be float. So, try with `method="first"` parameter.

In [5]:
df['Team'].value_counts()

Team
France            7
Argentina         7
Croatia           7
Morocco           7
Brazil            5
Portugal          5
England           5
Netherlands       5
Spain             4
Japan             4
Switzerland       4
Korea Republic    4
Australia         4
Poland            4
Senegal           4
United States     4
Mexico            3
Saudi Arabia      3
Denmark           3
Tunisia           3
Iran              3
Ecuador           3
Qatar             3
Wales             3
Canada            3
Belgium           3
Costa Rica        3
Germany           3
Uruguay           3
Cameroon          3
Ghana             3
Serbia            3
Name: count, dtype: int64

In [6]:
df['Team'].rank()

0       96.0
1       40.0
2       44.0
3       61.0
4      102.5
       ...
123     77.0
124     32.0
125     77.0
126      4.0
127     50.0
Name: Team, Length: 128, dtype: float64

### `Q-3:` Find out these below topics:
- The information about the Fifa worldcup dataset.
- The description about the Fifa worldcup dataset
- Check is there any missing values, if there is any missing values, fill that value with the average value for that particular column.
- Drop all the duplicate rows permanently.
- Drop the columns: "Sl No", "Match No.", "Red Cards" and "Pts" permanently.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    object
 3   Against                          128 non-null    object
 4   Group                            128 non-null    object
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), object(3)
memory usage: 38.1+ KB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Sl. No,128.0,64.500000,37.094474,1.0,32.75,64.5,96.25,128.0
Match No.,128.0,32.500000,18.545539,1.0,16.75,32.5,48.25,64.0
Goal,128.0,1.343750,1.342448,0.0,0.00,1.0,2.00,7.0
Possession (%),128.0,43.476562,11.442403,14.0,35.00,45.0,51.00,78.0
Inside Penalty Area,128.0,1.203125,1.324270,0.0,0.00,1.0,2.00,7.0
Outside Penalty Area,128.0,0.117188,0.322907,0.0,0.00,0.0,0.00,1.0
Assists,128.0,0.914062,1.150333,0.0,0.00,1.0,1.00,6.0
Total Attempts,128.0,11.257812,5.406683,0.0,7.75,10.0,14.00,32.0
On Target,128.0,4.007812,2.588576,0.0,2.00,4.0,6.00,13.0
Off Target,128.0,4.835938,2.610630,0.0,3.00,4.0,6.00,17.0
Target in Penalty,128.0,6.914062,3.998085,0.0,4.00,6.0,9.00,24.0
Target from Outside,128.0,4.343750,2.733397,0.0,3.00,4.0,5.00,15.0
Left Channel,128.0,13.562500,6.901729,2.0,8.00,12.0,18.00,36.0
Left Inside Channel,128.0,4.671875,2.886595,0.0,2.00,4.5,7.00,13.0
Central Channel,128.0,4.906250,3.080131,0.0,3.00,4.0,6.25,16.0
Right Inside Channel,128.0,4.648438,2.936573,0.0,3.00,4.0,6.00,19.0
Right Channel,128.0,12.234375,6.176517,1.0,8.00,11.0,16.25,29.0
Receptions MD,128.0,92.703125,29.440547,32.0,72.75,93.0,111.25,186.0
Receptions D,128.0,12.453125,18.152399,0.0,7.00,9.0,14.00,192.0
Attempted Line Breaks,128.0,169.281250,34.120661,56.0,149.50,170.5,188.00,259.0
Completed Line Breaks,128.0,109.476562,30.776298,19.0,87.75,106.0,129.00,192.0
Attempted Defensive Line Breaks,128.0,14.812500,7.230458,1.0,10.00,15.0,20.00,40.0
Completed Defensive Line Breaks,128.0,8.265625,5.101311,0.0,5.00,8.0,11.00,27.0
Yellow Cards,128.0,1.726562,1.514834,0.0,1.00,2.0,2.00,8.0
Red Cards,128.0,0.023438,0.151883,0.0,0.00,0.0,0.00,1.0
Fouls Against,128.0,12.320312,4.691983,0.0,9.00,12.0,15.00,30.0
Offsides,128.0,1.976562,1.731891,0.0,1.00,2.0,3.00,10.0
Passes,128.0,502.859375,160.160487,225.0,398.25,495.5,589.50,1070.0
Passes Completed,128.0,430.929688,160.893724,156.0,323.25,419.0,519.75,994.0
Crosses,128.0,19.523438,8.596799,4.0,13.00,19.0,24.00,53.0
Crosses Completed,128.0,4.898438,3.520111,0.0,3.00,4.0,6.00,25.0
Corners,128.0,4.468750,2.774852,0.0,2.00,4.0,6.00,14.0
Free Kicks,128.0,14.250000,4.712189,5.0,11.00,14.0,17.00,30.0
Penalties Scored,128.0,0.335938,0.941412,0.0,0.00,0.0,0.00,5.0
Pts,128.0,1.429688,1.389973,0.0,0.00,1.0,3.00,3.0

In [11]:
df.isnull().mean()*100

Sl. No                             0.0
Match No.                          0.0
Team                               0.0
Against                            0.0
Group                              0.0
Goal                               0.0
Possession (%)                     0.0
Inside Penalty Area                0.0
Outside Penalty Area               0.0
Assists                            0.0
Total Attempts                     0.0
On Target                          0.0
Off Target                         0.0
Target in Penalty                  0.0
Target from Outside                0.0
Left Channel                       0.0
Left Inside Channel                0.0
Central Channel                    0.0
Right Inside Channel               0.0
Right Channel                      0.0
Receptions MD                      0.0
Receptions D                       0.0
Attempted Line Breaks              0.0
Completed Line Breaks              0.0
Attempted Defensive Line Breaks    0.0
Completed Defensive Line Breaks    0.0
Yellow Cards                       0.0
Red Cards                          0.0
Fouls Against                      0.0
Offsides                           0.0
Passes                             0.0
Passes Completed                   0.0
Crosses                            0.0
Crosses Completed                  0.0
Corners                            0.0
Free Kicks                         0.0
Penalties Scored                   0.0
Pts                                0.0
dtype: float64

In [13]:
df[df.duplicated()]

Empty DataFrame
Columns: [Sl. No, Match No., Team, Against, Group, Goal, Possession (%), Inside Penalty Area, Outside Penalty Area, Assists, Total Attempts, On Target, Off Target, Target in Penalty, Target from Outside, Left Channel, Left Inside Channel, Central Channel, Right Inside Channel, Right Channel, Receptions MD, Receptions D, Attempted Line Breaks, Completed Line Breaks, Attempted Defensive Line Breaks, Completed Defensive Line Breaks, Yellow Cards, Red Cards, Fouls Against, Offsides, Passes, Passes Completed, Crosses, Crosses Completed, Corners, Free Kicks, Penalties Scored, Pts]
Index: []

In [17]:
#"Sl No", "Match No.", "Red Cards" and "Pts" permanently.
df.drop(columns=["Sl. No", "Match No.", "Red Cards","Pts"],inplace=True)

In [18]:
df.shape

(128, 34)

###`Q-4:` Do these below operations:
- Find out the rank based on the "Team" column and save the result by adding a new column named "Rank".
- Change the datatype of this column to integer by using `np.int16`
- Set the index of the DataFrame by using this "Rank" column permanently.
- After that, sort the dataframe based on the "Rank" index.

In [ ]:
# code here

## Questions on Titanic dataset.

You can get the dataset from [here](https://www.kaggle.com/competitions/titanic). This is the competition page on Kaggle. To download the dataset from here, I guess you have to register for the compition. So, do so and then download the dataset.

Also, for now you can use this url to read the dataset like before:
- dataset 1: https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv
- dataset 2: https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv

### `Q-5:` Do the below tasks:
1. With dataset 1, drop those records which only have missing values of the "Age" column permanently.

2. With the dataset 2, fill the missing values with 20 to the only "Age" column permanently.

In [27]:
url2="https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
url3="https://docs.google.com/spreadsheets/d/e/2PACX-1vQcPvQsSC9aNFogvbUG08nu0bGHlOclGYaOlhND_LE5Ff7ZnHQ5VYzAgpyT5XNklgiT54SsNgHePsUa/pub?gid=1656109608&single=true&output=csv"
df2=pd.read_csv(url2)
df3=pd.read_csv(url3)
df2.shape

(891, 12)

In [22]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df2.isnull().mean()*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          74.089636
Embarked        0.280112
dtype: float64

In [25]:
df2.dropna(subset=['Age'],inplace=True)

(714, 12)

In [28]:
df3.shape

(418, 11)

In [29]:
df3.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [33]:
df3.isnull().mean()*100

PassengerId     0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [32]:
df3.Age.fillna(20,inplace=True)

C:\Users\khadk\AppData\Local\Temp\ipykernel_7172\615650181.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3.Age.fillna(20,inplace=True)

## Questions on IPL wala dataset

matches dataset = https://drive.google.com/file/d/1yKVUuexl6lIKuFQy7uIPgDgXhJ0L4SIg/view?usp=share_link

Code to directly use in colab
```
ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRy2DUdUbaKx_Co9F0FSnIlyS-8kp4aKv_I0-qzNeghiZHAI_hw94gKG22XTxNJHMFnFVKsO4xWOdIs/pub?gid=1655759976&single=true&output=csv"

```

###`Q-6:` Make a dataframe of each team in IPL with details like - Team Name, Matches Played, Win%, Home Win%, Away Win%.
Show sorted dataframe on Win%

Replace old team name as new name before performing any tasks.
```
Delhi Daredevils ->Delhi Capitals
Kings XI Punjab -> Punjab Kings
Rising Pune Supergiants -> Rising Pune Supergiant
```

Note: Team1 represents Home team. Exclude not result matches.

In [ ]:
# code here

###`Q-7:` Venues with most "no result" matches.

In [ ]:
# code here

###`Q-8:` Player with most appearance in final match.

`Team1Players` and `Team2Players` have all players name. It is not a list of players name instead it is str. So handle it as string.

Hint: split and strip will help; Make a series of all players in final and do value counts

In [ ]:
# code here

###`Q-9:` IPL Point Table

Make a function `point_table` which take `season` as parameter and show points table in non-ascendng order of points and in ascending order of team name.

For winning - 2 Ponits;
For loosing - 0 Point
For not result both team gets 1 points.

Make dataframe which will have
`TeamName` `MatchesPlayed` `MatchesWon` `NoResult` `Points`
make `TeamName` as index.

```
season parametr should be one of these->
['2022', '2021', '2020/21', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2009/10', '2009', '2007/08']
```

Output of two Top 2 in season 2022
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points

Gujarat Titans	    16	   12	       0	     24
Rajasthan Royals	  17	   10	       0	     20

```

In [ ]:
# code here

###`Q-10:` IPL Point Table cont.
Extend the above IPL Point Table with an extra column as `SeasonPosition`

Team below top 4 after sorting on `Points` and then on `TeamName` Will have same `SeasonPosition` as there rank. use rank function.

Teams in Top four will have `SeasonPosition` as:
```
    'Winner' - Team won final
    'Runner' - Team lost Final
    3 - Losing Team in Qualifier2
    4 - Losing Team in Eliminator
```

For changing value of pariticular cell use `df.at[row_index, col_label] = value`

Output of two Top 2 in season 2022. Your result should have all teams.
```
TeamName    MatchesPlayed	MatchesWon	NoResult	Points   SeasonPosition

Gujarat Titans	    16	   12	       0	     24         Winner
Rajasthan Royals	  17	   10	       0	     20         Runner

```

Note: If you try to chnage value of view of any dataframe a warnig will be shown. To avoid it, make a copy of the dataframe you want to change in by `df.copy()`

In [ ]:
# code here